// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/auth/register/data/source/auth_remote_data_sourse_imlp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowers_ecommerce_app/core/network/api_services.dart' as _i4;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_body_dto.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_respone/register_respone_dto.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/products_detalis/data/model/get_specific_product_respone/get_specific_product_respone.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponeDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponeDto {
  _FakeRegisterResponeDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSpecificProductRespone_1 extends _i1.SmartFake
    implements _i3.GetSpecificProductRespone {
  _FakeGetSpecificProductRespone_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i4.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.RegisterResponeDto> register(_i6.RegisterBodyDTo? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i5.Future<_i2.RegisterResponeDto>.value(
              _FakeRegisterResponeDto_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.RegisterResponeDto>);

  @override
  _i5.Future<_i3.GetSpecificProductRespone> getSpecificProduct(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecificProduct, [productId]),
            returnValue: _i5.Future<_i3.GetSpecificProductRespone>.value(
              _FakeGetSpecificProductRespone_1(
                this,
                Invocation.method(#getSpecificProduct, [productId]),
              ),
            ),
          )
          as _i5.Future<_i3.GetSpecificProductRespone>);
}
