// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/profile/data/repo/get_user_data_repo_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/features/profile/data/model/user_response_dto.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/profile/data/remot_data_source/get_user_data_ds.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserResponseProfileDto_0 extends _i1.SmartFake
    implements _i2.UserResponseProfileDto {
  _FakeUserResponseProfileDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUserDataDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserDataDataSource extends _i1.Mock
    implements _i3.GetUserDataDataSource {
  MockGetUserDataDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserResponseProfileDto> getUserDataSource() =>
      (super.noSuchMethod(
            Invocation.method(#getUserDataSource, []),
            returnValue: _i4.Future<_i2.UserResponseProfileDto>.value(
              _FakeUserResponseProfileDto_0(
                this,
                Invocation.method(#getUserDataSource, []),
              ),
            ),
          )
          as _i4.Future<_i2.UserResponseProfileDto>);
}
