// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/products_detalis/presentation/view_model/cubit/product_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i5;
import 'package:flowers_ecommerce_app/features/products_detalis/domin/entites/product_entity.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/products_detalis/domin/repo/products_detalis_repo.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/products_detalis/domin/usecase/get_specific_product_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductsDetalisRepo_0 extends _i1.SmartFake
    implements _i2.ProductsDetalisRepo {
  _FakeProductsDetalisRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSpecificProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSpecificProductUsecase extends _i1.Mock
    implements _i3.GetSpecificProductUsecase {
  MockGetSpecificProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductsDetalisRepo get productsDetalisRepo =>
      (super.noSuchMethod(
            Invocation.getter(#productsDetalisRepo),
            returnValue: _FakeProductsDetalisRepo_0(
              this,
              Invocation.getter(#productsDetalisRepo),
            ),
          )
          as _i2.ProductsDetalisRepo);

  @override
  set productsDetalisRepo(_i2.ProductsDetalisRepo? _productsDetalisRepo) =>
      super.noSuchMethod(
        Invocation.setter(#productsDetalisRepo, _productsDetalisRepo),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.ApiResult<_i6.ProductEntity>> invok(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#invok, [id]),
            returnValue: _i4.Future<_i5.ApiResult<_i6.ProductEntity>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.ProductEntity>>(
                this,
                Invocation.method(#invok, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.ProductEntity>>);
}
