// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/products_detalis/data/repo/products_detalis_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/features/products_detalis/data/model/get_specific_product_respone/get_specific_product_respone.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/products_detalis/data/source/products_detalis_ds.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetSpecificProductRespone_0 extends _i1.SmartFake
    implements _i2.GetSpecificProductRespone {
  _FakeGetSpecificProductRespone_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsDetalisDs].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsDetalisDs extends _i1.Mock implements _i3.ProductsDetalisDs {
  MockProductsDetalisDs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GetSpecificProductRespone> getSpecificProduct(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecificProduct, [productId]),
            returnValue: _i4.Future<_i2.GetSpecificProductRespone>.value(
              _FakeGetSpecificProductRespone_0(
                this,
                Invocation.method(#getSpecificProduct, [productId]),
              ),
            ),
          )
          as _i4.Future<_i2.GetSpecificProductRespone>);
}
