// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/categories/presentation/category_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i5;
import 'package:flowers_ecommerce_app/features/categories/domain/entity/category_model.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/categories/domain/repository/get_all_category.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/categories/domain/usecases/get_all_category_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAllCategoryRepositoryContract_0 extends _i1.SmartFake
    implements _i2.GetAllCategoryRepositoryContract {
  _FakeGetAllCategoryRepositoryContract_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [GetAllCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoryUseCase extends _i1.Mock
    implements _i3.GetAllCategoryUseCase {
  MockGetAllCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAllCategoryRepositoryContract get getAllCategoryRepositoryContract =>
      (super.noSuchMethod(
            Invocation.getter(#getAllCategoryRepositoryContract),
            returnValue: _FakeGetAllCategoryRepositoryContract_0(
              this,
              Invocation.getter(#getAllCategoryRepositoryContract),
            ),
          )
          as _i2.GetAllCategoryRepositoryContract);

  @override
  set getAllCategoryRepositoryContract(
    _i2.GetAllCategoryRepositoryContract? _getAllCategoryRepositoryContract,
  ) => super.noSuchMethod(
    Invocation.setter(
      #getAllCategoryRepositoryContract,
      _getAllCategoryRepositoryContract,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<List<_i6.CategoryModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.ApiResult<List<_i6.CategoryModel>>>.value(
                  _i7.dummyValue<_i5.ApiResult<List<_i6.CategoryModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<List<_i6.CategoryModel>>>);
}
