// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/auth/login/data/data_sources/login_ds_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flowers_ecommerce_app/core/network/api_services.dart' as _i5;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/request/login_request_dto.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/responce/login_responce_dto.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_body_dto.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_respone/register_respone_dto.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/auth/reset_password/data/models/request/change_password_request_dto.dart'
    as _i9;
import 'package:flowers_ecommerce_app/features/auth/reset_password/data/models/response/change_password_response_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponceDto_0 extends _i1.SmartFake
    implements _i2.LoginResponceDto {
  _FakeLoginResponceDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponeDto_1 extends _i1.SmartFake
    implements _i3.RegisterResponeDto {
  _FakeRegisterResponeDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i5.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.LoginResponceDto> login(
    _i7.LoginRequestDto? loginRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequestDto]),
            returnValue: _i6.Future<_i2.LoginResponceDto>.value(
              _FakeLoginResponceDto_0(
                this,
                Invocation.method(#login, [loginRequestDto]),
              ),
            ),
          )
          as _i6.Future<_i2.LoginResponceDto>);

  @override
  _i6.Future<_i3.RegisterResponeDto> register(_i8.RegisterBodyDTo? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i6.Future<_i3.RegisterResponeDto>.value(
              _FakeRegisterResponeDto_1(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.RegisterResponeDto>);

  @override
  _i6.Future<_i4.ChangePasswordResponseDto> changePassword(
    _i9.ChangePasswordRequestDto? requestDto,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [requestDto, token]),
            returnValue: _i6.Future<_i4.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_2(
                this,
                Invocation.method(#changePassword, [requestDto, token]),
              ),
            ),
          )
          as _i6.Future<_i4.ChangePasswordResponseDto>);
}
