// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/auth/login/domain/view_model/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i5;
import 'package:flowers_ecommerce_app/core/helpers/shared_pref.dart' as _i9;
import 'package:flowers_ecommerce_app/features/auth/login/domain/entities/login_request_entity.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/auth/login/domain/entities/user_entitiy.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/auth/login/domain/use_case/login_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i3.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.UserEntity>> call(
    _i7.LoginRequestEntity? loginRequestEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [loginRequestEntity]),
            returnValue: _i4.Future<_i5.ApiResult<_i6.UserEntity>>.value(
              _i8.dummyValue<_i5.ApiResult<_i6.UserEntity>>(
                this,
                Invocation.method(#call, [loginRequestEntity]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.UserEntity>>);
}

/// A class which mocks [SharedPrefHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPrefHelper extends _i1.Mock implements _i9.SharedPrefHelper {
  MockSharedPrefHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_0(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i2.SharedPreferences);

  @override
  _i4.Future<bool> saveData({required String? key, required dynamic val}) =>
      (super.noSuchMethod(
            Invocation.method(#saveData, [], {#key: key, #val: val}),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  Object? getData({required String? key}) =>
      (super.noSuchMethod(Invocation.method(#getData, [], {#key: key}))
          as Object?);

  @override
  _i4.Future<bool> removeData({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#removeData, [], {#key: key}),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
