// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/auth/change_password/presentation/manager/change_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i4;
import 'package:flowers_ecommerce_app/features/auth/change_password/domain/entities/change_password_request_entity.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/auth/change_password/domain/entities/change_password_response_entity.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/auth/change_password/domain/use_cases/change_password_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i2.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.ChangePasswordResponseEntity>> invoke(
    _i6.ChangePasswordRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [request]),
            returnValue:
                _i3.Future<
                  _i4.ApiResult<_i5.ChangePasswordResponseEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.ApiResult<_i5.ChangePasswordResponseEntity>
                  >(this, Invocation.method(#invoke, [request])),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.ChangePasswordResponseEntity>>);
}
