// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/address_details/presentation/manager/add_new_address_cubit/add_new_address_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i4;
import 'package:flowers_ecommerce_app/features/address_details/domain/entities/request/add_new_address_request_entity.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/address_details/domain/entities/response/addresses_response_entity.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/address_details/domain/entities/response/area_response_entity.dart'
    as _i11;
import 'package:flowers_ecommerce_app/features/address_details/domain/entities/response/cities_response_entity.dart'
    as _i9;
import 'package:flowers_ecommerce_app/features/address_details/domain/use_cases/add_new_address_use_case.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/address_details/domain/use_cases/get_areas_use_case.dart'
    as _i10;
import 'package:flowers_ecommerce_app/features/address_details/domain/use_cases/get_cities_use_case.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AddNewAddressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddNewAddressUseCase extends _i1.Mock
    implements _i2.AddNewAddressUseCase {
  MockAddNewAddressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.AddressesResponseEntity>> invoke(
    _i6.AddNewAddressRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i5.AddressesResponseEntity>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i5.AddressesResponseEntity>>(
                    this,
                    Invocation.method(#invoke, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.AddressesResponseEntity>>);
}

/// A class which mocks [GetCitiesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCitiesUseCase extends _i1.Mock implements _i8.GetCitiesUseCase {
  MockGetCitiesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i9.CitiesResponseEntity>> invoke() =>
      (super.noSuchMethod(
            Invocation.method(#invoke, []),
            returnValue:
                _i3.Future<_i4.ApiResult<_i9.CitiesResponseEntity>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i9.CitiesResponseEntity>>(
                    this,
                    Invocation.method(#invoke, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i9.CitiesResponseEntity>>);
}

/// A class which mocks [GetAreasUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAreasUseCase extends _i1.Mock implements _i10.GetAreasUseCase {
  MockGetAreasUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i11.AreaResponseEntity>> invoke() =>
      (super.noSuchMethod(
            Invocation.method(#invoke, []),
            returnValue:
                _i3.Future<_i4.ApiResult<_i11.AreaResponseEntity>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i11.AreaResponseEntity>>(
                    this,
                    Invocation.method(#invoke, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i11.AreaResponseEntity>>);
}
