// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/profile/presentation/view_model/profile_setting_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i5;
import 'package:flowers_ecommerce_app/core/helpers/shared_pref.dart' as _i12;
import 'package:flowers_ecommerce_app/features/profile/domain/entities/about_us_entity.dart'
    as _i11;
import 'package:flowers_ecommerce_app/features/profile/domain/entities/term_entity.dart'
    as _i9;
import 'package:flowers_ecommerce_app/features/profile/domain/entities/user_entity.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/profile/domain/usecase/contect_terms_use_case.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/profile/domain/usecase/content_about_us_use_case.dart'
    as _i10;
import 'package:flowers_ecommerce_app/features/profile/domain/usecase/get_user_data_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUserDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserDataUseCase extends _i1.Mock
    implements _i3.GetUserDataUseCase {
  MockGetUserDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.UserProfileEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.ApiResult<_i6.UserProfileEntity>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.UserProfileEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.UserProfileEntity>>);
}

/// A class which mocks [GetTermsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTermsUseCase extends _i1.Mock implements _i8.GetTermsUseCase {
  MockGetTermsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i9.TermEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i9.TermEntity>>.value(
              <_i9.TermEntity>[],
            ),
          )
          as _i4.Future<List<_i9.TermEntity>>);
}

/// A class which mocks [GetAboutUsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAboutUsUseCase extends _i1.Mock implements _i10.GetAboutUsUseCase {
  MockGetAboutUsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i11.AboutUsEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i11.AboutUsEntity>>.value(
              <_i11.AboutUsEntity>[],
            ),
          )
          as _i4.Future<List<_i11.AboutUsEntity>>);
}

/// A class which mocks [SharedPrefHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPrefHelper extends _i1.Mock implements _i12.SharedPrefHelper {
  MockSharedPrefHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_0(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i2.SharedPreferences);

  @override
  _i4.Future<bool> saveData({required String? key, required dynamic val}) =>
      (super.noSuchMethod(
            Invocation.method(#saveData, [], {#key: key, #val: val}),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  Object? getData({required String? key}) =>
      (super.noSuchMethod(Invocation.method(#getData, [], {#key: key}))
          as Object?);

  @override
  _i4.Future<bool> removeData({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#removeData, [], {#key: key}),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
