// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/products_detalis/data/source/products_detalis_ds_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i28;

import 'package:flowers_ecommerce_app/core/network/api_services.dart' as _i27;
import 'package:flowers_ecommerce_app/features/add_to_cart/data/model/add_product_body.dart'
    as _i34;
import 'package:flowers_ecommerce_app/features/add_to_cart/data/model/add_product_respone.dart'
    as _i19;
import 'package:flowers_ecommerce_app/features/address_details/data/models/request/add_new_address_request_dto.dart'
    as _i35;
import 'package:flowers_ecommerce_app/features/address_details/data/models/response/addresses_response_dto.dart'
    as _i21;
import 'package:flowers_ecommerce_app/features/auth/change_password/data/models/request/change_password_request_dto.dart'
    as _i32;
import 'package:flowers_ecommerce_app/features/auth/change_password/data/models/response/change_password_response_dto.dart'
    as _i15;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/email_verify_model.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/forget_pass_model.dart'
    as _i4;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/reset_pass_model.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/request/login_request_dto.dart'
    as _i29;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/responce/login_responce_dto.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/auth/logout/data/models/logout_response_dto.dart'
    as _i25;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_body_dto.dart'
    as _i30;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_respone/register_respone_dto.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/cart/data/models/delete_cart_item_respone/delete_cart_item_respone.dart'
    as _i11;
import 'package:flowers_ecommerce_app/features/cart/data/models/updeate_cart_prouduct_quantity_body.dart'
    as _i31;
import 'package:flowers_ecommerce_app/features/cart/data/models/updeate_proudact_quantity_respone/updeate_proudact_quantity_respone.dart'
    as _i10;
import 'package:flowers_ecommerce_app/features/cart/data/models/user_cart/user_cart.dart'
    as _i9;
import 'package:flowers_ecommerce_app/features/categories/data/models/response/category_response.dart'
    as _i14;
import 'package:flowers_ecommerce_app/features/categories/data/models/response/product_response.dart'
    as _i13;
import 'package:flowers_ecommerce_app/features/checkout/data/model/get_user_addreses_respone/get_user_addreses_respone.dart'
    as _i18;
import 'package:flowers_ecommerce_app/features/home_screen/data/model/home_response_dto.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/occasions/data/models/occasions_response_dto.dart'
    as _i12;
import 'package:flowers_ecommerce_app/features/orders/data/model/user_orders_respone/user_orders_respone.dart'
    as _i20;
import 'package:flowers_ecommerce_app/features/payment/data/model/request/payment_request_model_dto.dart'
    as _i33;
import 'package:flowers_ecommerce_app/features/payment/data/model/responce/card_pay_responce/card_pay_responce_model_dto.dart'
    as _i16;
import 'package:flowers_ecommerce_app/features/payment/data/model/responce/cash_pay_responce/cash_pay_responce_model_dto.dart'
    as _i17;
import 'package:flowers_ecommerce_app/features/products_detalis/data/model/get_specific_product_respone/get_specific_product_respone.dart'
    as _i26;
import 'package:flowers_ecommerce_app/features/profile/data/model/user_response_dto.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/saved_addresses/data/models/get_user_address_dto.dart'
    as _i23;
import 'package:flowers_ecommerce_app/features/saved_addresses/data/models/user_address_dto.dart'
    as _i22;
import 'package:flowers_ecommerce_app/features/search/data/models/reponse/search_response.dart'
    as _i24;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponceDto_0 extends _i1.SmartFake
    implements _i2.LoginResponceDto {
  _FakeLoginResponceDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeResponseDto_1 extends _i1.SmartFake
    implements _i3.HomeResponseDto {
  _FakeHomeResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordModel_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordModel {
  _FakeForgetPasswordModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailVerifyModel_3 extends _i1.SmartFake
    implements _i5.EmailVerifyModel {
  _FakeEmailVerifyModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordModel_4 extends _i1.SmartFake
    implements _i6.ResetPasswordModel {
  _FakeResetPasswordModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponeDto_5 extends _i1.SmartFake
    implements _i7.RegisterResponeDto {
  _FakeRegisterResponeDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponseProfileDto_6 extends _i1.SmartFake
    implements _i8.UserResponseProfileDto {
  _FakeUserResponseProfileDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCartDto_7 extends _i1.SmartFake implements _i9.UserCartDto {
  _FakeUserCartDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdeateProudactQuantityRespone_8 extends _i1.SmartFake
    implements _i10.UpdeateProudactQuantityRespone {
  _FakeUpdeateProudactQuantityRespone_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeDeleteCartItemRespone_9 extends _i1.SmartFake
    implements _i11.DeleteCartItemRespone {
  _FakeDeleteCartItemRespone_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOccasionsResponseDto_10 extends _i1.SmartFake
    implements _i12.OccasionsResponseDto {
  _FakeOccasionsResponseDto_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductResponse_11 extends _i1.SmartFake
    implements _i13.ProductResponse {
  _FakeProductResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryResponse_12 extends _i1.SmartFake
    implements _i14.CategoryResponse {
  _FakeCategoryResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_13 extends _i1.SmartFake
    implements _i15.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCardPayResponceModelDto_14 extends _i1.SmartFake
    implements _i16.CardPayResponceModelDto {
  _FakeCardPayResponceModelDto_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCashPayResponceModelDto_15 extends _i1.SmartFake
    implements _i17.CashPayResponceModelDto {
  _FakeCashPayResponceModelDto_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserAddresesRespone_16 extends _i1.SmartFake
    implements _i18.GetUserAddresesRespone {
  _FakeGetUserAddresesRespone_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddProductRespone_17 extends _i1.SmartFake
    implements _i19.AddProductRespone {
  _FakeAddProductRespone_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserOrdersRespone_18 extends _i1.SmartFake
    implements _i20.UserOrdersRespone {
  _FakeUserOrdersRespone_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressesResponseDto_19 extends _i1.SmartFake
    implements _i21.AddressesResponseDto {
  _FakeAddressesResponseDto_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserAddressDto_20 extends _i1.SmartFake
    implements _i22.UserAddressDto {
  _FakeUserAddressDto_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserAddressDto_21 extends _i1.SmartFake
    implements _i23.GetUserAddressDto {
  _FakeGetUserAddressDto_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchResponse_22 extends _i1.SmartFake
    implements _i24.SearchResponse {
  _FakeSearchResponse_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutResponseDto_23 extends _i1.SmartFake
    implements _i25.LogoutResponseDto {
  _FakeLogoutResponseDto_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSpecificProductRespone_24 extends _i1.SmartFake
    implements _i26.GetSpecificProductRespone {
  _FakeGetSpecificProductRespone_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i27.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i28.Future<_i2.LoginResponceDto> login(
    _i29.LoginRequestDto? loginRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequestDto]),
            returnValue: _i28.Future<_i2.LoginResponceDto>.value(
              _FakeLoginResponceDto_0(
                this,
                Invocation.method(#login, [loginRequestDto]),
              ),
            ),
          )
          as _i28.Future<_i2.LoginResponceDto>);

  @override
  _i28.Future<_i3.HomeResponseDto> homeData() =>
      (super.noSuchMethod(
            Invocation.method(#homeData, []),
            returnValue: _i28.Future<_i3.HomeResponseDto>.value(
              _FakeHomeResponseDto_1(this, Invocation.method(#homeData, [])),
            ),
          )
          as _i28.Future<_i3.HomeResponseDto>);

  @override
  _i28.Future<_i4.ForgetPasswordModel> forgetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [body]),
            returnValue: _i28.Future<_i4.ForgetPasswordModel>.value(
              _FakeForgetPasswordModel_2(
                this,
                Invocation.method(#forgetPassword, [body]),
              ),
            ),
          )
          as _i28.Future<_i4.ForgetPasswordModel>);

  @override
  _i28.Future<_i5.EmailVerifyModel> verifyResetCode(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [body]),
            returnValue: _i28.Future<_i5.EmailVerifyModel>.value(
              _FakeEmailVerifyModel_3(
                this,
                Invocation.method(#verifyResetCode, [body]),
              ),
            ),
          )
          as _i28.Future<_i5.EmailVerifyModel>);

  @override
  _i28.Future<_i6.ResetPasswordModel> resetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [body]),
            returnValue: _i28.Future<_i6.ResetPasswordModel>.value(
              _FakeResetPasswordModel_4(
                this,
                Invocation.method(#resetPassword, [body]),
              ),
            ),
          )
          as _i28.Future<_i6.ResetPasswordModel>);

  @override
  _i28.Future<_i7.RegisterResponeDto> register(_i30.RegisterBodyDTo? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i28.Future<_i7.RegisterResponeDto>.value(
              _FakeRegisterResponeDto_5(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i28.Future<_i7.RegisterResponeDto>);

  @override
  _i28.Future<_i8.UserResponseProfileDto> userData() =>
      (super.noSuchMethod(
            Invocation.method(#userData, []),
            returnValue: _i28.Future<_i8.UserResponseProfileDto>.value(
              _FakeUserResponseProfileDto_6(
                this,
                Invocation.method(#userData, []),
              ),
            ),
          )
          as _i28.Future<_i8.UserResponseProfileDto>);

  @override
  _i28.Future<_i9.UserCartDto> getUserCart() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCart, []),
            returnValue: _i28.Future<_i9.UserCartDto>.value(
              _FakeUserCartDto_7(this, Invocation.method(#getUserCart, [])),
            ),
          )
          as _i28.Future<_i9.UserCartDto>);

  @override
  _i28.Future<_i10.UpdeateProudactQuantityRespone> updeateCartProudctQuantity(
    String? id,
    _i31.UpdeateCartProuductQuantityBody? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updeateCartProudctQuantity, [id, body]),
            returnValue: _i28.Future<_i10.UpdeateProudactQuantityRespone>.value(
              _FakeUpdeateProudactQuantityRespone_8(
                this,
                Invocation.method(#updeateCartProudctQuantity, [id, body]),
              ),
            ),
          )
          as _i28.Future<_i10.UpdeateProudactQuantityRespone>);

  @override
  _i28.Future<_i11.DeleteCartItemRespone> deleteCartProudct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCartProudct, [id]),
            returnValue: _i28.Future<_i11.DeleteCartItemRespone>.value(
              _FakeDeleteCartItemRespone_9(
                this,
                Invocation.method(#deleteCartProudct, [id]),
              ),
            ),
          )
          as _i28.Future<_i11.DeleteCartItemRespone>);

  @override
  _i28.Future<_i12.OccasionsResponseDto> getOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasions, []),
            returnValue: _i28.Future<_i12.OccasionsResponseDto>.value(
              _FakeOccasionsResponseDto_10(
                this,
                Invocation.method(#getOccasions, []),
              ),
            ),
          )
          as _i28.Future<_i12.OccasionsResponseDto>);

  @override
  _i28.Future<_i13.ProductResponse> getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue: _i28.Future<_i13.ProductResponse>.value(
              _FakeProductResponse_11(
                this,
                Invocation.method(#getAllProducts, []),
              ),
            ),
          )
          as _i28.Future<_i13.ProductResponse>);

  @override
  _i28.Future<_i14.CategoryResponse> getAllCategory() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategory, []),
            returnValue: _i28.Future<_i14.CategoryResponse>.value(
              _FakeCategoryResponse_12(
                this,
                Invocation.method(#getAllCategory, []),
              ),
            ),
          )
          as _i28.Future<_i14.CategoryResponse>);

  @override
  _i28.Future<_i15.ChangePasswordResponseDto> changePassword(
    _i32.ChangePasswordRequestDto? requestDto,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [requestDto, token]),
            returnValue: _i28.Future<_i15.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_13(
                this,
                Invocation.method(#changePassword, [requestDto, token]),
              ),
            ),
          )
          as _i28.Future<_i15.ChangePasswordResponseDto>);

  @override
  _i28.Future<_i16.CardPayResponceModelDto> paymentCard(
    _i33.PaymentRequestModelDto? paymentRequestModelDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#paymentCard, [paymentRequestModelDto]),
            returnValue: _i28.Future<_i16.CardPayResponceModelDto>.value(
              _FakeCardPayResponceModelDto_14(
                this,
                Invocation.method(#paymentCard, [paymentRequestModelDto]),
              ),
            ),
          )
          as _i28.Future<_i16.CardPayResponceModelDto>);

  @override
  _i28.Future<_i17.CashPayResponceModelDto> paymentCash(
    _i33.PaymentRequestModelDto? paymentRequestModelDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#paymentCash, [paymentRequestModelDto]),
            returnValue: _i28.Future<_i17.CashPayResponceModelDto>.value(
              _FakeCashPayResponceModelDto_15(
                this,
                Invocation.method(#paymentCash, [paymentRequestModelDto]),
              ),
            ),
          )
          as _i28.Future<_i17.CashPayResponceModelDto>);

  @override
  _i28.Future<_i18.GetUserAddresesRespone> getLoggedUserAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserAddresses, []),
            returnValue: _i28.Future<_i18.GetUserAddresesRespone>.value(
              _FakeGetUserAddresesRespone_16(
                this,
                Invocation.method(#getLoggedUserAddresses, []),
              ),
            ),
          )
          as _i28.Future<_i18.GetUserAddresesRespone>);

  @override
  _i28.Future<_i19.AddProductRespone> addToCart(
    _i34.AddProductBody? addProductBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [addProductBody]),
            returnValue: _i28.Future<_i19.AddProductRespone>.value(
              _FakeAddProductRespone_17(
                this,
                Invocation.method(#addToCart, [addProductBody]),
              ),
            ),
          )
          as _i28.Future<_i19.AddProductRespone>);

  @override
  _i28.Future<_i20.UserOrdersRespone> getUserOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, []),
            returnValue: _i28.Future<_i20.UserOrdersRespone>.value(
              _FakeUserOrdersRespone_18(
                this,
                Invocation.method(#getUserOrders, []),
              ),
            ),
          )
          as _i28.Future<_i20.UserOrdersRespone>);

  @override
  _i28.Future<_i21.AddressesResponseDto> addNewAddress(
    String? token,
    _i35.AddNewAddressRequestDto? requestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNewAddress, [token, requestDto]),
            returnValue: _i28.Future<_i21.AddressesResponseDto>.value(
              _FakeAddressesResponseDto_19(
                this,
                Invocation.method(#addNewAddress, [token, requestDto]),
              ),
            ),
          )
          as _i28.Future<_i21.AddressesResponseDto>);

  @override
  _i28.Future<_i22.UserAddressDto> removeAddress(String? token, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAddress, [token, id]),
            returnValue: _i28.Future<_i22.UserAddressDto>.value(
              _FakeUserAddressDto_20(
                this,
                Invocation.method(#removeAddress, [token, id]),
              ),
            ),
          )
          as _i28.Future<_i22.UserAddressDto>);

  @override
  _i28.Future<_i23.GetUserAddressDto> getAllAddresses(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getAllAddresses, [token]),
            returnValue: _i28.Future<_i23.GetUserAddressDto>.value(
              _FakeGetUserAddressDto_21(
                this,
                Invocation.method(#getAllAddresses, [token]),
              ),
            ),
          )
          as _i28.Future<_i23.GetUserAddressDto>);

  @override
  _i28.Future<_i24.SearchResponse> search(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#search, [keyword]),
            returnValue: _i28.Future<_i24.SearchResponse>.value(
              _FakeSearchResponse_22(
                this,
                Invocation.method(#search, [keyword]),
              ),
            ),
          )
          as _i28.Future<_i24.SearchResponse>);

  @override
  _i28.Future<_i25.LogoutResponseDto> logout(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [token]),
            returnValue: _i28.Future<_i25.LogoutResponseDto>.value(
              _FakeLogoutResponseDto_23(
                this,
                Invocation.method(#logout, [token]),
              ),
            ),
          )
          as _i28.Future<_i25.LogoutResponseDto>);

  @override
  _i28.Future<_i26.GetSpecificProductRespone> getSpecificProduct(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecificProduct, [productId]),
            returnValue: _i28.Future<_i26.GetSpecificProductRespone>.value(
              _FakeGetSpecificProductRespone_24(
                this,
                Invocation.method(#getSpecificProduct, [productId]),
              ),
            ),
          )
          as _i28.Future<_i26.GetSpecificProductRespone>);
}
