// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/cart/presentation/view_model/cubit/cart_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i5;
import 'package:flowers_ecommerce_app/features/cart/data/models/delete_cart_item_respone/delete_cart_item_respone.dart'
    as _i9;
import 'package:flowers_ecommerce_app/features/cart/data/models/updeate_cart_prouduct_quantity_body.dart'
    as _i12;
import 'package:flowers_ecommerce_app/features/cart/data/models/updeate_proudact_quantity_respone/updeate_proudact_quantity_respone.dart'
    as _i11;
import 'package:flowers_ecommerce_app/features/cart/domin/entities/user_cart.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/cart/domin/repo/cart_repo.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/cart/domin/usecase/delete_cart_usecase.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/cart/domin/usecase/get_user_carts_usecase.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/cart/domin/usecase/updeate_cart_product_quantity_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCartRepo_0 extends _i1.SmartFake implements _i2.CartRepo {
  _FakeCartRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUserCartsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserCartsUsecase extends _i1.Mock
    implements _i3.GetUserCartsUsecase {
  MockGetUserCartsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CartRepo get cartRepo =>
      (super.noSuchMethod(
            Invocation.getter(#cartRepo),
            returnValue: _FakeCartRepo_0(this, Invocation.getter(#cartRepo)),
          )
          as _i2.CartRepo);

  @override
  _i4.Future<_i5.ApiResult<_i6.UserCart>> invok() =>
      (super.noSuchMethod(
            Invocation.method(#invok, []),
            returnValue: _i4.Future<_i5.ApiResult<_i6.UserCart>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.UserCart>>(
                this,
                Invocation.method(#invok, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.UserCart>>);
}

/// A class which mocks [DeleteCartUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCartUsecase extends _i1.Mock implements _i8.DeleteCartUsecase {
  MockDeleteCartUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CartRepo get cartRepo =>
      (super.noSuchMethod(
            Invocation.getter(#cartRepo),
            returnValue: _FakeCartRepo_0(this, Invocation.getter(#cartRepo)),
          )
          as _i2.CartRepo);

  @override
  _i4.Future<_i5.ApiResult<_i9.DeleteCartItemRespone>> invok(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#invok, [id]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i9.DeleteCartItemRespone>>.value(
                  _i7.dummyValue<_i5.ApiResult<_i9.DeleteCartItemRespone>>(
                    this,
                    Invocation.method(#invok, [id]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i9.DeleteCartItemRespone>>);
}

/// A class which mocks [UpdeateCartProductQuantityUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdeateCartProductQuantityUsecase extends _i1.Mock
    implements _i10.UpdeateCartProductQuantityUsecase {
  MockUpdeateCartProductQuantityUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CartRepo get cartRepo =>
      (super.noSuchMethod(
            Invocation.getter(#cartRepo),
            returnValue: _FakeCartRepo_0(this, Invocation.getter(#cartRepo)),
          )
          as _i2.CartRepo);

  @override
  set cartRepo(_i2.CartRepo? _cartRepo) => super.noSuchMethod(
    Invocation.setter(#cartRepo, _cartRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i11.UpdeateProudactQuantityRespone>> invok(
    String? id,
    _i12.UpdeateCartProuductQuantityBody? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invok, [id, quantity]),
            returnValue:
                _i4.Future<
                  _i5.ApiResult<_i11.UpdeateProudactQuantityRespone>
                >.value(
                  _i7.dummyValue<
                    _i5.ApiResult<_i11.UpdeateProudactQuantityRespone>
                  >(this, Invocation.method(#invok, [id, quantity])),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i11.UpdeateProudactQuantityRespone>>);
}
