// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/feature/forget_password/presentation/forget_pass_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i7;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/email_verify_model.dart'
    as _i11;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/forget_pass_model.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/reset_pass_model.dart'
    as _i13;
import 'package:flowers_ecommerce_app/features/auth/forget_password/domain/repository/email_verify_repo_contract.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/auth/forget_password/domain/repository/forget_pass_repo_contract.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/auth/forget_password/domain/repository/reset_pass_repo_contract.dart'
    as _i4;
import 'package:flowers_ecommerce_app/features/auth/forget_password/domain/usecases/email_verify_usecase.dart'
    as _i10;
import 'package:flowers_ecommerce_app/features/auth/forget_password/domain/usecases/forget_pass_usecase.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/auth/forget_password/domain/usecases/reset_pass_usecase.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordRepoContract_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordRepoContract {
  _FakeForgetPasswordRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailVerifyRepoContract_1 extends _i1.SmartFake
    implements _i3.EmailVerifyRepoContract {
  _FakeEmailVerifyRepoContract_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordRepoContract_2 extends _i1.SmartFake
    implements _i4.ResetPasswordRepoContract {
  _FakeResetPasswordRepoContract_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordUseCase extends _i1.Mock
    implements _i5.ForgetPasswordUseCase {
  MockForgetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepoContract get forgetPasswordRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordRepoContract),
            returnValue: _FakeForgetPasswordRepoContract_0(
              this,
              Invocation.getter(#forgetPasswordRepoContract),
            ),
          )
          as _i2.ForgetPasswordRepoContract);

  @override
  set forgetPasswordRepoContract(
    _i2.ForgetPasswordRepoContract? _forgetPasswordRepoContract,
  ) => super.noSuchMethod(
    Invocation.setter(#forgetPasswordRepoContract, _forgetPasswordRepoContract),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.ApiResult<_i8.ForgetPasswordModel>> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue:
                _i6.Future<_i7.ApiResult<_i8.ForgetPasswordModel>>.value(
                  _i9.dummyValue<_i7.ApiResult<_i8.ForgetPasswordModel>>(
                    this,
                    Invocation.method(#call, [email]),
                  ),
                ),
          )
          as _i6.Future<_i7.ApiResult<_i8.ForgetPasswordModel>>);
}

/// A class which mocks [EmailVerifyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailVerifyUseCase extends _i1.Mock
    implements _i10.EmailVerifyUseCase {
  MockEmailVerifyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.EmailVerifyRepoContract get emailVerifyRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#emailVerifyRepoContract),
            returnValue: _FakeEmailVerifyRepoContract_1(
              this,
              Invocation.getter(#emailVerifyRepoContract),
            ),
          )
          as _i3.EmailVerifyRepoContract);

  @override
  set emailVerifyRepoContract(
    _i3.EmailVerifyRepoContract? _emailVerifyRepoContract,
  ) => super.noSuchMethod(
    Invocation.setter(#emailVerifyRepoContract, _emailVerifyRepoContract),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.ApiResult<_i11.EmailVerifyModel>> call(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#call, [code]),
            returnValue: _i6.Future<_i7.ApiResult<_i11.EmailVerifyModel>>.value(
              _i9.dummyValue<_i7.ApiResult<_i11.EmailVerifyModel>>(
                this,
                Invocation.method(#call, [code]),
              ),
            ),
          )
          as _i6.Future<_i7.ApiResult<_i11.EmailVerifyModel>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i12.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ResetPasswordRepoContract get resetPasswordRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#resetPasswordRepoContract),
            returnValue: _FakeResetPasswordRepoContract_2(
              this,
              Invocation.getter(#resetPasswordRepoContract),
            ),
          )
          as _i4.ResetPasswordRepoContract);

  @override
  set resetPasswordRepoContract(
    _i4.ResetPasswordRepoContract? _resetPasswordRepoContract,
  ) => super.noSuchMethod(
    Invocation.setter(#resetPasswordRepoContract, _resetPasswordRepoContract),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.ApiResult<_i13.ResetPasswordModel>> call(
    String? email,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email, newPassword]),
            returnValue:
                _i6.Future<_i7.ApiResult<_i13.ResetPasswordModel>>.value(
                  _i9.dummyValue<_i7.ApiResult<_i13.ResetPasswordModel>>(
                    this,
                    Invocation.method(#call, [email, newPassword]),
                  ),
                ),
          )
          as _i6.Future<_i7.ApiResult<_i13.ResetPasswordModel>>);
}
