// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/occasions/data/repositories/occasions_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/core/errors/internet_connection.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/occasions/data/data_sources/occasions_ds.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/occasions/data/models/occasions_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOccasionsResponseDto_0 extends _i1.SmartFake
    implements _i2.OccasionsResponseDto {
  _FakeOccasionsResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OccasionsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOccasionsDataSource extends _i1.Mock
    implements _i3.OccasionsDataSource {
  MockOccasionsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.OccasionsResponseDto> getOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasions, []),
            returnValue: _i4.Future<_i2.OccasionsResponseDto>.value(
              _FakeOccasionsResponseDto_0(
                this,
                Invocation.method(#getOccasions, []),
              ),
            ),
          )
          as _i4.Future<_i2.OccasionsResponseDto>);
}

/// A class which mocks [NetworkConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkConnection extends _i1.Mock implements _i5.NetworkConnection {
  MockNetworkConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
