// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/cart/domin/usecase/get_user_carts_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i4;
import 'package:flowers_ecommerce_app/features/cart/data/models/delete_cart_item_respone/delete_cart_item_respone.dart'
    as _i9;
import 'package:flowers_ecommerce_app/features/cart/data/models/updeate_cart_prouduct_quantity_body.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/cart/data/models/updeate_proudact_quantity_respone/updeate_proudact_quantity_respone.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/cart/domin/entities/user_cart.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/cart/domin/repo/cart_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CartRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepo extends _i1.Mock implements _i2.CartRepo {
  MockCartRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.UserCart>> getUserCart() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCart, []),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserCart>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserCart>>(
                this,
                Invocation.method(#getUserCart, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserCart>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.UpdeateProudactQuantityRespone>>
  updeateCartProudctQuantity(
    String? id,
    _i8.UpdeateCartProuductQuantityBody? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updeateCartProudctQuantity, [id, body]),
            returnValue:
                _i3.Future<
                  _i4.ApiResult<_i7.UpdeateProudactQuantityRespone>
                >.value(
                  _i6.dummyValue<
                    _i4.ApiResult<_i7.UpdeateProudactQuantityRespone>
                  >(
                    this,
                    Invocation.method(#updeateCartProudctQuantity, [id, body]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i7.UpdeateProudactQuantityRespone>>);

  @override
  _i3.Future<_i4.ApiResult<_i9.DeleteCartItemRespone>> deleteCartProudct(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCartProudct, [id]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i9.DeleteCartItemRespone>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i9.DeleteCartItemRespone>>(
                    this,
                    Invocation.method(#deleteCartProudct, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i9.DeleteCartItemRespone>>);
}
