// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/auth/change_password/data/data_sources/change_password_ds_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;

import 'package:flowers_ecommerce_app/core/network/api_services.dart' as _i19;
import 'package:flowers_ecommerce_app/core/services/token_service.dart' as _i25;
import 'package:flowers_ecommerce_app/features/auth/change_password/data/models/request/change_password_request_dto.dart'
    as _i24;
import 'package:flowers_ecommerce_app/features/auth/change_password/data/models/response/change_password_response_dto.dart'
    as _i17;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/email_verify_model.dart'
    as _i4;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/forget_pass_model.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/reset_pass_model.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/request/login_request_dto.dart'
    as _i21;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/responce/login_responce_dto.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/auth/logout/data/models/logout_response_dto.dart'
    as _i18;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_body_dto.dart'
    as _i22;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_respone/register_respone_dto.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/cart/data/models/delete_cart_item_respone/delete_cart_item_respone.dart'
    as _i15;
import 'package:flowers_ecommerce_app/features/cart/data/models/updeate_cart_prouduct_quantity_body.dart'
    as _i23;
import 'package:flowers_ecommerce_app/features/cart/data/models/updeate_proudact_quantity_respone/updeate_proudact_quantity_respone.dart'
    as _i14;
import 'package:flowers_ecommerce_app/features/cart/data/models/user_cart/user_cart.dart'
    as _i13;
import 'package:flowers_ecommerce_app/features/categories/data/models/response/category_response.dart'
    as _i10;
import 'package:flowers_ecommerce_app/features/categories/data/models/response/product_response.dart'
    as _i9;
import 'package:flowers_ecommerce_app/features/edit_profile/data/models/response/edit_profile_response.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/main_layout/tabs/home_screen/data/model/home_response_dto.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/occasions/data/models/occasions_response_dto.dart'
    as _i12;
import 'package:flowers_ecommerce_app/features/products_detalis/data/model/get_specific_product_respone/get_specific_product_respone.dart'
    as _i11;
import 'package:flowers_ecommerce_app/features/profile/data/model/user_response_dto.dart'
    as _i16;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponceDto_0 extends _i1.SmartFake
    implements _i2.LoginResponceDto {
  _FakeLoginResponceDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordModel_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordModel {
  _FakeForgetPasswordModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailVerifyModel_2 extends _i1.SmartFake
    implements _i4.EmailVerifyModel {
  _FakeEmailVerifyModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordModel_3 extends _i1.SmartFake
    implements _i5.ResetPasswordModel {
  _FakeResetPasswordModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponeDto_4 extends _i1.SmartFake
    implements _i6.RegisterResponeDto {
  _FakeRegisterResponeDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEditProfileResponse_5 extends _i1.SmartFake
    implements _i7.EditProfileResponse {
  _FakeEditProfileResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeResponseDto_6 extends _i1.SmartFake
    implements _i8.HomeResponseDto {
  _FakeHomeResponseDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductResponse_7 extends _i1.SmartFake
    implements _i9.ProductResponse {
  _FakeProductResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryResponse_8 extends _i1.SmartFake
    implements _i10.CategoryResponse {
  _FakeCategoryResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSpecificProductRespone_9 extends _i1.SmartFake
    implements _i11.GetSpecificProductRespone {
  _FakeGetSpecificProductRespone_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOccasionsResponseDto_10 extends _i1.SmartFake
    implements _i12.OccasionsResponseDto {
  _FakeOccasionsResponseDto_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCartDto_11 extends _i1.SmartFake implements _i13.UserCartDto {
  _FakeUserCartDto_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdeateProudactQuantityRespone_12 extends _i1.SmartFake
    implements _i14.UpdeateProudactQuantityRespone {
  _FakeUpdeateProudactQuantityRespone_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeDeleteCartItemRespone_13 extends _i1.SmartFake
    implements _i15.DeleteCartItemRespone {
  _FakeDeleteCartItemRespone_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponseDto_14 extends _i1.SmartFake
    implements _i16.UserResponseDto {
  _FakeUserResponseDto_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_15 extends _i1.SmartFake
    implements _i17.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutResponseDto_16 extends _i1.SmartFake
    implements _i18.LogoutResponseDto {
  _FakeLogoutResponseDto_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i19.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i2.LoginResponceDto> login(
    _i21.LoginRequestDto? loginRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequestDto]),
            returnValue: _i20.Future<_i2.LoginResponceDto>.value(
              _FakeLoginResponceDto_0(
                this,
                Invocation.method(#login, [loginRequestDto]),
              ),
            ),
          )
          as _i20.Future<_i2.LoginResponceDto>);

  @override
  _i20.Future<_i3.ForgetPasswordModel> forgetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [body]),
            returnValue: _i20.Future<_i3.ForgetPasswordModel>.value(
              _FakeForgetPasswordModel_1(
                this,
                Invocation.method(#forgetPassword, [body]),
              ),
            ),
          )
          as _i20.Future<_i3.ForgetPasswordModel>);

  @override
  _i20.Future<_i4.EmailVerifyModel> verifyResetCode(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [body]),
            returnValue: _i20.Future<_i4.EmailVerifyModel>.value(
              _FakeEmailVerifyModel_2(
                this,
                Invocation.method(#verifyResetCode, [body]),
              ),
            ),
          )
          as _i20.Future<_i4.EmailVerifyModel>);

  @override
  _i20.Future<_i5.ResetPasswordModel> resetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [body]),
            returnValue: _i20.Future<_i5.ResetPasswordModel>.value(
              _FakeResetPasswordModel_3(
                this,
                Invocation.method(#resetPassword, [body]),
              ),
            ),
          )
          as _i20.Future<_i5.ResetPasswordModel>);

  @override
  _i20.Future<_i6.RegisterResponeDto> register(_i22.RegisterBodyDTo? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i20.Future<_i6.RegisterResponeDto>.value(
              _FakeRegisterResponeDto_4(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i20.Future<_i6.RegisterResponeDto>);

  @override
  _i20.Future<_i7.EditProfileResponse> editProfile(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [body]),
            returnValue: _i20.Future<_i7.EditProfileResponse>.value(
              _FakeEditProfileResponse_5(
                this,
                Invocation.method(#editProfile, [body]),
              ),
            ),
          )
          as _i20.Future<_i7.EditProfileResponse>);

  @override
  _i20.Future<_i8.HomeResponseDto> homeData() =>
      (super.noSuchMethod(
            Invocation.method(#homeData, []),
            returnValue: _i20.Future<_i8.HomeResponseDto>.value(
              _FakeHomeResponseDto_6(this, Invocation.method(#homeData, [])),
            ),
          )
          as _i20.Future<_i8.HomeResponseDto>);

  @override
  _i20.Future<_i9.ProductResponse> getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue: _i20.Future<_i9.ProductResponse>.value(
              _FakeProductResponse_7(
                this,
                Invocation.method(#getAllProducts, []),
              ),
            ),
          )
          as _i20.Future<_i9.ProductResponse>);

  @override
  _i20.Future<_i10.CategoryResponse> getAllCategory() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategory, []),
            returnValue: _i20.Future<_i10.CategoryResponse>.value(
              _FakeCategoryResponse_8(
                this,
                Invocation.method(#getAllCategory, []),
              ),
            ),
          )
          as _i20.Future<_i10.CategoryResponse>);

  @override
  _i20.Future<_i11.GetSpecificProductRespone> getSpecificProduct(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecificProduct, [productId]),
            returnValue: _i20.Future<_i11.GetSpecificProductRespone>.value(
              _FakeGetSpecificProductRespone_9(
                this,
                Invocation.method(#getSpecificProduct, [productId]),
              ),
            ),
          )
          as _i20.Future<_i11.GetSpecificProductRespone>);

  @override
  _i20.Future<_i12.OccasionsResponseDto> getOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasions, []),
            returnValue: _i20.Future<_i12.OccasionsResponseDto>.value(
              _FakeOccasionsResponseDto_10(
                this,
                Invocation.method(#getOccasions, []),
              ),
            ),
          )
          as _i20.Future<_i12.OccasionsResponseDto>);

  @override
  _i20.Future<_i13.UserCartDto> getUserCart() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCart, []),
            returnValue: _i20.Future<_i13.UserCartDto>.value(
              _FakeUserCartDto_11(this, Invocation.method(#getUserCart, [])),
            ),
          )
          as _i20.Future<_i13.UserCartDto>);

  @override
  _i20.Future<_i14.UpdeateProudactQuantityRespone> updeateCartProudctQuantity(
    String? id,
    _i23.UpdeateCartProuductQuantityBody? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updeateCartProudctQuantity, [id, body]),
            returnValue: _i20.Future<_i14.UpdeateProudactQuantityRespone>.value(
              _FakeUpdeateProudactQuantityRespone_12(
                this,
                Invocation.method(#updeateCartProudctQuantity, [id, body]),
              ),
            ),
          )
          as _i20.Future<_i14.UpdeateProudactQuantityRespone>);

  @override
  _i20.Future<_i15.DeleteCartItemRespone> deleteCartProudct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCartProudct, [id]),
            returnValue: _i20.Future<_i15.DeleteCartItemRespone>.value(
              _FakeDeleteCartItemRespone_13(
                this,
                Invocation.method(#deleteCartProudct, [id]),
              ),
            ),
          )
          as _i20.Future<_i15.DeleteCartItemRespone>);

  @override
  _i20.Future<_i16.UserResponseDto> userData() =>
      (super.noSuchMethod(
            Invocation.method(#userData, []),
            returnValue: _i20.Future<_i16.UserResponseDto>.value(
              _FakeUserResponseDto_14(this, Invocation.method(#userData, [])),
            ),
          )
          as _i20.Future<_i16.UserResponseDto>);

  @override
  _i20.Future<_i17.ChangePasswordResponseDto> changePassword(
    _i24.ChangePasswordRequestDto? requestDto,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [requestDto, token]),
            returnValue: _i20.Future<_i17.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_15(
                this,
                Invocation.method(#changePassword, [requestDto, token]),
              ),
            ),
          )
          as _i20.Future<_i17.ChangePasswordResponseDto>);

  @override
  _i20.Future<_i18.LogoutResponseDto> logout(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [token]),
            returnValue: _i20.Future<_i18.LogoutResponseDto>.value(
              _FakeLogoutResponseDto_16(
                this,
                Invocation.method(#logout, [token]),
              ),
            ),
          )
          as _i20.Future<_i18.LogoutResponseDto>);
}

/// A class which mocks [TokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenService extends _i1.Mock implements _i25.TokenService {
  MockTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isTokenSaved =>
      (super.noSuchMethod(Invocation.getter(#isTokenSaved), returnValue: false)
          as bool);

  @override
  _i20.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i20.Future<String?>.value(),
          )
          as _i20.Future<String?>);

  @override
  _i20.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}
