// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/auth/change_password/data/data_sources/change_password_ds_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
<<<<<<< HEAD
import 'dart:async' as _i11;

import 'package:flowers_ecommerce_app/core/network/api_services.dart' as _i10;
import 'package:flowers_ecommerce_app/core/services/token_service.dart' as _i15;
import 'package:flowers_ecommerce_app/features/auth/change_password/data/models/request/change_password_request_dto.dart'
    as _i14;
import 'package:flowers_ecommerce_app/features/auth/change_password/data/models/response/change_password_response_dto.dart'
    as _i9;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/email_verify_model.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/forget_pass_model.dart'
    as _i4;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/reset_pass_model.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/request/login_request_dto.dart'
    as _i12;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/responce/login_responce_dto.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_body_dto.dart'
    as _i13;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_respone/register_respone_dto.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/home_screen/data/model/home_response_dto.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/profile/data/model/user_response_dto.dart'
    as _i8;
=======
import 'dart:async' as _i9;

import 'package:flowers_ecommerce_app/core/network/api_services.dart' as _i8;
import 'package:flowers_ecommerce_app/core/services/token_service.dart' as _i13;
import 'package:flowers_ecommerce_app/features/auth/change_password/data/models/request/change_password_request_dto.dart'
    as _i12;
import 'package:flowers_ecommerce_app/features/auth/change_password/data/models/response/change_password_response_dto.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/email_verify_model.dart'
    as _i4;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/forget_pass_model.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/auth/forget_password/datasource/models/reset_pass_model.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/request/login_request_dto.dart'
    as _i10;
import 'package:flowers_ecommerce_app/features/auth/login/data/model/responce/login_responce_dto.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_body_dto.dart'
    as _i11;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_respone/register_respone_dto.dart'
    as _i6;
>>>>>>> origin/feature/ECOM-12-MostSelling
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponceDto_0 extends _i1.SmartFake
    implements _i2.LoginResponceDto {
  _FakeLoginResponceDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

<<<<<<< HEAD
class _FakeHomeResponseDto_1 extends _i1.SmartFake
    implements _i3.HomeResponseDto {
  _FakeHomeResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordModel_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordModel {
  _FakeForgetPasswordModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailVerifyModel_3 extends _i1.SmartFake
    implements _i5.EmailVerifyModel {
  _FakeEmailVerifyModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordModel_4 extends _i1.SmartFake
    implements _i6.ResetPasswordModel {
  _FakeResetPasswordModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponeDto_5 extends _i1.SmartFake
    implements _i7.RegisterResponeDto {
  _FakeRegisterResponeDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponseProfileDto_6 extends _i1.SmartFake
    implements _i8.UserResponseProfileDto {
  _FakeUserResponseProfileDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_7 extends _i1.SmartFake
    implements _i9.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_7(Object parent, Invocation parentInvocation)
=======
class _FakeForgetPasswordModel_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordModel {
  _FakeForgetPasswordModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailVerifyModel_2 extends _i1.SmartFake
    implements _i4.EmailVerifyModel {
  _FakeEmailVerifyModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordModel_3 extends _i1.SmartFake
    implements _i5.ResetPasswordModel {
  _FakeResetPasswordModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponeDto_4 extends _i1.SmartFake
    implements _i6.RegisterResponeDto {
  _FakeRegisterResponeDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_5 extends _i1.SmartFake
    implements _i7.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_5(Object parent, Invocation parentInvocation)
>>>>>>> origin/feature/ECOM-12-MostSelling
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
<<<<<<< HEAD
class MockApiServices extends _i1.Mock implements _i10.ApiServices {
=======
class MockApiServices extends _i1.Mock implements _i8.ApiServices {
>>>>>>> origin/feature/ECOM-12-MostSelling
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
<<<<<<< HEAD
  _i11.Future<_i2.LoginResponceDto> login(
    _i12.LoginRequestDto? loginRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequestDto]),
            returnValue: _i11.Future<_i2.LoginResponceDto>.value(
=======
  _i9.Future<_i2.LoginResponceDto> login(
    _i10.LoginRequestDto? loginRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequestDto]),
            returnValue: _i9.Future<_i2.LoginResponceDto>.value(
>>>>>>> origin/feature/ECOM-12-MostSelling
              _FakeLoginResponceDto_0(
                this,
                Invocation.method(#login, [loginRequestDto]),
              ),
            ),
          )
<<<<<<< HEAD
          as _i11.Future<_i2.LoginResponceDto>);

  @override
  _i11.Future<_i3.HomeResponseDto> homeData() =>
      (super.noSuchMethod(
            Invocation.method(#homeData, []),
            returnValue: _i11.Future<_i3.HomeResponseDto>.value(
              _FakeHomeResponseDto_1(this, Invocation.method(#homeData, [])),
            ),
          )
          as _i11.Future<_i3.HomeResponseDto>);

  @override
  _i11.Future<_i4.ForgetPasswordModel> forgetPassword(
=======
          as _i9.Future<_i2.LoginResponceDto>);

  @override
  _i9.Future<_i3.ForgetPasswordModel> forgetPassword(
>>>>>>> origin/feature/ECOM-12-MostSelling
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [body]),
<<<<<<< HEAD
            returnValue: _i11.Future<_i4.ForgetPasswordModel>.value(
              _FakeForgetPasswordModel_2(
=======
            returnValue: _i9.Future<_i3.ForgetPasswordModel>.value(
              _FakeForgetPasswordModel_1(
>>>>>>> origin/feature/ECOM-12-MostSelling
                this,
                Invocation.method(#forgetPassword, [body]),
              ),
            ),
          )
<<<<<<< HEAD
          as _i11.Future<_i4.ForgetPasswordModel>);

  @override
  _i11.Future<_i5.EmailVerifyModel> verifyResetCode(
=======
          as _i9.Future<_i3.ForgetPasswordModel>);

  @override
  _i9.Future<_i4.EmailVerifyModel> verifyResetCode(
>>>>>>> origin/feature/ECOM-12-MostSelling
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [body]),
<<<<<<< HEAD
            returnValue: _i11.Future<_i5.EmailVerifyModel>.value(
              _FakeEmailVerifyModel_3(
=======
            returnValue: _i9.Future<_i4.EmailVerifyModel>.value(
              _FakeEmailVerifyModel_2(
>>>>>>> origin/feature/ECOM-12-MostSelling
                this,
                Invocation.method(#verifyResetCode, [body]),
              ),
            ),
          )
<<<<<<< HEAD
          as _i11.Future<_i5.EmailVerifyModel>);

  @override
  _i11.Future<_i6.ResetPasswordModel> resetPassword(
=======
          as _i9.Future<_i4.EmailVerifyModel>);

  @override
  _i9.Future<_i5.ResetPasswordModel> resetPassword(
>>>>>>> origin/feature/ECOM-12-MostSelling
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [body]),
<<<<<<< HEAD
            returnValue: _i11.Future<_i6.ResetPasswordModel>.value(
              _FakeResetPasswordModel_4(
=======
            returnValue: _i9.Future<_i5.ResetPasswordModel>.value(
              _FakeResetPasswordModel_3(
>>>>>>> origin/feature/ECOM-12-MostSelling
                this,
                Invocation.method(#resetPassword, [body]),
              ),
            ),
          )
<<<<<<< HEAD
          as _i11.Future<_i6.ResetPasswordModel>);

  @override
  _i11.Future<_i7.RegisterResponeDto> register(_i13.RegisterBodyDTo? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i11.Future<_i7.RegisterResponeDto>.value(
              _FakeRegisterResponeDto_5(
=======
          as _i9.Future<_i5.ResetPasswordModel>);

  @override
  _i9.Future<_i6.RegisterResponeDto> register(_i11.RegisterBodyDTo? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i9.Future<_i6.RegisterResponeDto>.value(
              _FakeRegisterResponeDto_4(
>>>>>>> origin/feature/ECOM-12-MostSelling
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
<<<<<<< HEAD
          as _i11.Future<_i7.RegisterResponeDto>);

  @override
  _i11.Future<_i8.UserResponseProfileDto> userData() =>
      (super.noSuchMethod(
            Invocation.method(#userData, []),
            returnValue: _i11.Future<_i8.UserResponseProfileDto>.value(
              _FakeUserResponseProfileDto_6(
                this,
                Invocation.method(#userData, []),
              ),
            ),
          )
          as _i11.Future<_i8.UserResponseProfileDto>);

  @override
  _i11.Future<_i9.ChangePasswordResponseDto> changePassword(
    _i14.ChangePasswordRequestDto? requestDto,
=======
          as _i9.Future<_i6.RegisterResponeDto>);

  @override
  _i9.Future<_i7.ChangePasswordResponseDto> changePassword(
    _i12.ChangePasswordRequestDto? requestDto,
>>>>>>> origin/feature/ECOM-12-MostSelling
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [requestDto, token]),
<<<<<<< HEAD
            returnValue: _i11.Future<_i9.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_7(
=======
            returnValue: _i9.Future<_i7.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_5(
>>>>>>> origin/feature/ECOM-12-MostSelling
                this,
                Invocation.method(#changePassword, [requestDto, token]),
              ),
            ),
          )
<<<<<<< HEAD
          as _i11.Future<_i9.ChangePasswordResponseDto>);
=======
          as _i9.Future<_i7.ChangePasswordResponseDto>);
>>>>>>> origin/feature/ECOM-12-MostSelling
}

/// A class which mocks [TokenService].
///
/// See the documentation for Mockito's code generation for more information.
<<<<<<< HEAD
class MockTokenService extends _i1.Mock implements _i15.TokenService {
=======
class MockTokenService extends _i1.Mock implements _i13.TokenService {
>>>>>>> origin/feature/ECOM-12-MostSelling
  MockTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isTokenSaved =>
      (super.noSuchMethod(Invocation.getter(#isTokenSaved), returnValue: false)
          as bool);

  @override
<<<<<<< HEAD
  _i11.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
=======
  _i9.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
>>>>>>> origin/feature/ECOM-12-MostSelling
}
