// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/profile/domain/usecase/get_user_data_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i4;
import 'package:flowers_ecommerce_app/features/profile/domain/entities/user_entity.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/profile/domain/repo/get_user_data_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetUserDataRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserDataRepo extends _i1.Mock implements _i2.GetUserDataRepo {
  MockGetUserDataRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.UserProfileEntity>> getUserDataRepo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserDataRepo, []),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserProfileEntity>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserProfileEntity>>(
                this,
                Invocation.method(#getUserDataRepo, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserProfileEntity>>);
}
