// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/saved_addresses/data/repositories/saved_address_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowers_ecommerce_app/features/saved_addresses/data/data_sources/saved_address_ds.dart'
    as _i4;
import 'package:flowers_ecommerce_app/features/saved_addresses/data/models/get_user_address_dto.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/saved_addresses/data/models/user_address_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserAddressDto_0 extends _i1.SmartFake
    implements _i2.UserAddressDto {
  _FakeUserAddressDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserAddressDto_1 extends _i1.SmartFake
    implements _i3.GetUserAddressDto {
  _FakeGetUserAddressDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SavedAddressDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedAddressDataSource extends _i1.Mock
    implements _i4.SavedAddressDataSource {
  MockSavedAddressDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserAddressDto> removeAddress(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAddress, [id]),
            returnValue: _i5.Future<_i2.UserAddressDto>.value(
              _FakeUserAddressDto_0(
                this,
                Invocation.method(#removeAddress, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.UserAddressDto>);

  @override
  _i5.Future<_i3.GetUserAddressDto> getAllAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAddresses, []),
            returnValue: _i5.Future<_i3.GetUserAddressDto>.value(
              _FakeGetUserAddressDto_1(
                this,
                Invocation.method(#getAllAddresses, []),
              ),
            ),
          )
          as _i5.Future<_i3.GetUserAddressDto>);
}
