// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/auth/register/presentation/view_model/register_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i5;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_body.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/auth/register/data/model/register_respone/register_respone.dart'
    as _i6;
import 'package:flowers_ecommerce_app/features/auth/register/domin/repo/auth_repo.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/auth/register/domin/usecase/register_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepo_0 extends _i1.SmartFake implements _i2.AuthRepo {
  _FakeAuthRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUsecase extends _i1.Mock implements _i3.RegisterUsecase {
  MockRegisterUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepo get authRepo =>
      (super.noSuchMethod(
            Invocation.getter(#authRepo),
            returnValue: _FakeAuthRepo_0(this, Invocation.getter(#authRepo)),
          )
          as _i2.AuthRepo);

  @override
  _i4.Future<_i5.ApiResult<_i6.RegisterRespone>> invok(
    _i7.RegisterBody? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invok, [request]),
            returnValue: _i4.Future<_i5.ApiResult<_i6.RegisterRespone>>.value(
              _i8.dummyValue<_i5.ApiResult<_i6.RegisterRespone>>(
                this,
                Invocation.method(#invok, [request]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.RegisterRespone>>);
}
