// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/address_details/data/repositories/add_new_address_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flowers_ecommerce_app/features/address_details/data/data_sources/add_new_address_ds.dart'
    as _i5;
import 'package:flowers_ecommerce_app/features/address_details/data/data_sources/local_ds/get_cities_and_areas_local_ds.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/address_details/data/models/request/add_new_address_request_dto.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/address_details/data/models/response/addresses_response_dto.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/address_details/data/models/response/area_response_dto.dart'
    as _i4;
import 'package:flowers_ecommerce_app/features/address_details/data/models/response/cities_response_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAddressesResponseDto_0 extends _i1.SmartFake
    implements _i2.AddressesResponseDto {
  _FakeAddressesResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCitiesResponseDto_1 extends _i1.SmartFake
    implements _i3.CitiesResponseDto {
  _FakeCitiesResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAreaResponseDto_2 extends _i1.SmartFake
    implements _i4.AreaResponseDto {
  _FakeAreaResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddNewAddressDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddNewAddressDataSource extends _i1.Mock
    implements _i5.AddNewAddressDataSource {
  MockAddNewAddressDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AddressesResponseDto> addNewAddress(
    _i7.AddNewAddressRequestDto? requestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNewAddress, [requestDto]),
            returnValue: _i6.Future<_i2.AddressesResponseDto>.value(
              _FakeAddressesResponseDto_0(
                this,
                Invocation.method(#addNewAddress, [requestDto]),
              ),
            ),
          )
          as _i6.Future<_i2.AddressesResponseDto>);
}

/// A class which mocks [GetCitiesAndAreasLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCitiesAndAreasLocalDataSource extends _i1.Mock
    implements _i8.GetCitiesAndAreasLocalDataSource {
  MockGetCitiesAndAreasLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.CitiesResponseDto> getCities() =>
      (super.noSuchMethod(
            Invocation.method(#getCities, []),
            returnValue: _i6.Future<_i3.CitiesResponseDto>.value(
              _FakeCitiesResponseDto_1(this, Invocation.method(#getCities, [])),
            ),
          )
          as _i6.Future<_i3.CitiesResponseDto>);

  @override
  _i6.Future<_i4.AreaResponseDto> getAreas() =>
      (super.noSuchMethod(
            Invocation.method(#getAreas, []),
            returnValue: _i6.Future<_i4.AreaResponseDto>.value(
              _FakeAreaResponseDto_2(this, Invocation.method(#getAreas, [])),
            ),
          )
          as _i6.Future<_i4.AreaResponseDto>);
}
