// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/auth/logout/data/repositories/logout_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_ecommerce_app/core/services/token_service.dart' as _i5;
import 'package:flowers_ecommerce_app/features/auth/logout/data/data_sources/logout_ds.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/auth/logout/data/models/logout_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogoutResponseDto_0 extends _i1.SmartFake
    implements _i2.LogoutResponseDto {
  _FakeLogoutResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogoutDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutDataSource extends _i1.Mock implements _i3.LogoutDataSource {
  MockLogoutDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LogoutResponseDto> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.LogoutResponseDto>.value(
              _FakeLogoutResponseDto_0(this, Invocation.method(#logout, [])),
            ),
          )
          as _i4.Future<_i2.LogoutResponseDto>);
}

/// A class which mocks [TokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenService extends _i1.Mock implements _i5.TokenService {
  MockTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isTokenSaved =>
      (super.noSuchMethod(Invocation.getter(#isTokenSaved), returnValue: false)
          as bool);

  @override
  _i4.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
