// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_ecommerce_app/test/features/edit_profile/presentation/edit_profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i12;

import 'package:flowers_ecommerce_app/core/errors/api_results.dart' as _i6;
import 'package:flowers_ecommerce_app/features/edit_profile/domain/entity/edit_profile_request.dart'
    as _i8;
import 'package:flowers_ecommerce_app/features/edit_profile/domain/entity/edit_profile_response_entity.dart'
    as _i7;
import 'package:flowers_ecommerce_app/features/edit_profile/domain/entity/upload_photo_entity.dart'
    as _i11;
import 'package:flowers_ecommerce_app/features/edit_profile/domain/repository/edti_profile.dart'
    as _i2;
import 'package:flowers_ecommerce_app/features/edit_profile/domain/repository/upload_photo_repo_contract.dart'
    as _i3;
import 'package:flowers_ecommerce_app/features/edit_profile/domain/usecases/edit_profile_usecase.dart'
    as _i4;
import 'package:flowers_ecommerce_app/features/edit_profile/domain/usecases/upload_photo_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEditProfileRepositoryContract_0 extends _i1.SmartFake
    implements _i2.EditProfileRepositoryContract {
  _FakeEditProfileRepositoryContract_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeUploadPhotoRepoContract_1 extends _i1.SmartFake
    implements _i3.UploadPhotoRepoContract {
  _FakeUploadPhotoRepoContract_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i4.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EditProfileRepositoryContract get editProfileRepositoryContract =>
      (super.noSuchMethod(
            Invocation.getter(#editProfileRepositoryContract),
            returnValue: _FakeEditProfileRepositoryContract_0(
              this,
              Invocation.getter(#editProfileRepositoryContract),
            ),
          )
          as _i2.EditProfileRepositoryContract);

  @override
  set editProfileRepositoryContract(
    _i2.EditProfileRepositoryContract? _editProfileRepositoryContract,
  ) => super.noSuchMethod(
    Invocation.setter(
      #editProfileRepositoryContract,
      _editProfileRepositoryContract,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i6.ApiResult<_i7.EditProfileResponseEntity>> call(
    _i8.EditProfileRequest? editProfileRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [editProfileRequest]),
            returnValue:
                _i5.Future<_i6.ApiResult<_i7.EditProfileResponseEntity>>.value(
                  _i9.dummyValue<_i6.ApiResult<_i7.EditProfileResponseEntity>>(
                    this,
                    Invocation.method(#call, [editProfileRequest]),
                  ),
                ),
          )
          as _i5.Future<_i6.ApiResult<_i7.EditProfileResponseEntity>>);
}

/// A class which mocks [UploadPhotoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadPhotoUseCase extends _i1.Mock
    implements _i10.UploadPhotoUseCase {
  MockUploadPhotoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UploadPhotoRepoContract get uploadPhotoRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#uploadPhotoRepoContract),
            returnValue: _FakeUploadPhotoRepoContract_1(
              this,
              Invocation.getter(#uploadPhotoRepoContract),
            ),
          )
          as _i3.UploadPhotoRepoContract);

  @override
  set uploadPhotoRepoContract(
    _i3.UploadPhotoRepoContract? _uploadPhotoRepoContract,
  ) => super.noSuchMethod(
    Invocation.setter(#uploadPhotoRepoContract, _uploadPhotoRepoContract),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i6.ApiResult<_i11.UploadPhotoEntity>> call(_i12.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#call, [file]),
            returnValue:
                _i5.Future<_i6.ApiResult<_i11.UploadPhotoEntity>>.value(
                  _i9.dummyValue<_i6.ApiResult<_i11.UploadPhotoEntity>>(
                    this,
                    Invocation.method(#call, [file]),
                  ),
                ),
          )
          as _i5.Future<_i6.ApiResult<_i11.UploadPhotoEntity>>);
}
